channels:
- conda-forge
dependencies:
- bidict =0.23.1
- h5py =3.15.1
- hatchling =1.27.0
- hatch-vcs =0.5.0
- numpy =2.3.4
- pygtrie =2.5.0
- pyiron_snippets =1.0.2
- python >=3.11,<3.15
- ipytree =0.2.2
- traitlets =5.14.3
