channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- bidict =0.23.1
- h5py =3.15.1
- hatchling =1.28.0
- hatch-vcs =0.5.0
- hypothesis =6.151.5
- numpy =2.4.2
- pygtrie =2.5.0
- pyiron_snippets =1.0.2
- python >=3.11,<3.15
